name             "ak-bzr"
maintainer       "Akretion"
maintainer_email "contact@akretion.com"
license          "All rights reserved"
description      "customized LWRP for bzr SCM"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends          "python"
depends          "apt"
depends          "ak-tools"
